project:
  type: website

website:
  title: "matdmiller.com"
  reader-mode: true
  search: false
  favicon: logo.png
  twitter-card: true
  site-url: https://matdmiller.com
  open-graph: true
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: https://blog.matdmiller.com
        text: Blog
      - href: https://blog.matdmiller.com/about
        text: About
    right: 
      - icon: github
        href: https://github.com/matdmiller
      - icon: twitter 
        href: https://twitter.com/matdmiller
  page-footer: "Copyright 2024, Mat Miller"

format:
  html:
    theme:
      light: lux
      dark: lux
#    css: styles.css
    toc: true