project:
  type: website

website:
  title: "matdmiller.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://blog.matdmiller.com
        text: Blog
      - href: https://blog.matdmiller.com/about
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true